#ifndef _CONSTANTS
  #define _CONSTANTS
  #define PIZZA_KEYWORD "pizza"
  #define PAN_KEYWORD "pan"
  #define MASA_KEYWORD "masa"
  #define MASA_KEYWORD_LEN 4
  #define PAN_KEYWORD_LEN 3
  #define PIZZA_KEYWORD_LEN 5
  #define DEFAULT_BUFFER_LEN 15
  #define TIEMPO_COCCION_PANADERO 0.5
  #define PIZZA_TIEMPO_LOWER_UNIFORM_VALUE 0.5
  #define PIZZA_TIEMPO_UPPER_UNIFORM_VALUE 1.0
  #define TIEMPO_ALIMENTAR_MASA_MADRE 0.1
  #define ETAPAS_MASA_MADRE 7
  #define MAXIMO_SIMULTANEO_POR_COCINERO 12
  #define MASAS_MADRE_INICIALES 10
#endif
