#ifndef _MENSAJES
  #define _MENSAJES
  #define DEBUG_TAG L"[🧰 DEBUG] "
  #define INFO_TAG L"[🗃️ INFO]  "
  #define ERROR_TAG L"[❌ ERROR] "
  #define ERROR_TAG L"[❌ ERROR] "
  #define FATAL_TAG L"[💀 FATAL] "
  #define FATAL_TAG_NOT_UNICODE "[FATAL] "
  #define LOG_DATA_FORMAT "[%s:%d, pid: %ld] "
  #define CANTIDAD_RECEPCIONISTAS L"🛎️ La cantidad de recepcionistas es %d"
  #define CANTIDAD_PIZZEROS L"🍕 La cantidad de pizzeros es %d"
  #define CANTIDAD_PANADEROS L"🍞 La cantidad de panaderos es %d"
  #define INICIADO_RECEPCIONISTA L"🛎️ Iniciando recepcionista"
  #define RECEPCIONISTA_PIZZA_PEDIDA L"🛎️🍕 Pedido por pizza recibido"
  #define RECEPCIONISTA_PAN_PEDIDO L"🛎️🍞 Pedido por pan recibido"
  #define RECEPCIONISTA_STOP L"🛎️🛑 No se encontraron más trabajos pendientes"
  #define ERROR_PEDIDO_NO_COMPRENDIDO L"Se recibio un pedido incomprensible '%s'"
  #define FATAL_SIGINT "Sigint atrapado, terminando proceso"
  #define FATAL_MALLOC "Error alocando recursos"
  #define FATAL_LECTURA_RECEPCIONISTA "Error en el recepcionista al leer archivo de entrada"
  #define FATAL_ARCHIVO_LOG "No se pudo abrir el archivo para guardar el log"
  #define FATAL_CAMPOS_NEGATIVOS "Uno de los parametros obligatorios es 0 o negativo"
  #define FATAL_PARAMETROS_FALTANTES "No se especificaron todos los parametros obligatorios"
  #define FATAL_ARCHIVO_ENTRADA "No fue posible abrir el archivo de entrada"
  #define FATAL_RESOURCE_MANAGER "Error al inicializar el administrador de memoria"
  #define FATAL_ACQUIRE_LOCK "Error fatal al adquirir lock"
  #define FATAL_ERROR_CHILD "Error fatal en proceso hijo, terminando todas las ejecuciones"
  #define FATAL_ERROR_WAIT "Error esperando proceso hijo, terminando todas las ejecuciones"
#endif
