#ifndef _MENSAJES
  #define _MENSAJES
  #define DEBUG_TAG L"[🧰 DEBUG] "
  #define INFO_TAG L"[🗃️ INFO]  "
  #define ERROR_TAG L"[❌ ERROR] "
  #define LOG_DATA_FORMAT L"[%s:%d, pid: %ld] "
  #define CANTIDAD_RECEPCIONISTAS L"🛎️ La cantidad de recepcionistas es %d"
  #define CANTIDAD_PIZZEROS L"🍕 La cantidad de pizzeros es %d"
  #define CANTIDAD_PANADEROS L"🍞 La cantidad de panaderos es %d"
  #define INICIADO_RECEPCIONISTA L"🛎️ Iniciando recepcionista"
  #define RECEPCIONISTA_PIZZA_PEDIDA L"🛎️🍕 Pedido por pizza recibido"
  #define RECEPCIONISTA_PAN_PEDIDO L"🛎️🍞 Pedido por pan recibido"
  #define RECEPCIONISTA_STOP L"🛎️🛑 No se encontraron más trabajos pendientes"
  #define ERROR_PEDIDO_NO_COMPRENDIDO L"Se recibio un pedido incomprensible '%s'"
  #define ERROR_MALLOC L"Error alocando recursos en pid %ld"
  #define ERROR_LECTURA_RECEPCIONISTA L"Error en el recepcionista al leer archivo de entrada"
  #define ERROR_ARCHIVO_LOG "No se pudo abrir el archivo para guardar el log"
  #define ERROR_CAMPOS_NEGATIVOS "Uno de los parametros obligatorios es 0 o negativo"
  #define ERROR_PARAMETROS_FALTANTES "No se especificaron todos los parametros obligatorios"
  #define ERROR_ARCHIVO_ENTRADA "No fue posible abrir el archivo de entrada"
#endif
